project:
  type: website
  output-dir: docs

website:
  title: "nmoraescommit"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
  page-footer:
    background: light
    left: Copyright 2024, Naomi Moraes
    right: This website is built with {{< fa brands github title="The GitHub octocat logo" >}}
format:
  html:
    theme: styles.scss
    mainfont: Montserrat
    toc: false
    page-layout: full
editor: visual

